using System;
using AlibabaCloud.SDK.VIAPI.Utils;

/// <summary>
/// Summary description for Class1
/// </summary>
public class AliyunApplet
{
    public static AliyunApplet instance;

    /// <summary>
    /// Safety attributes generated by Aliyun.
    /// </summary>
    private string key, secret;
    /// <summary>
    /// The local path of the last image uploaded to Aliyun.
    /// </summary>
    private string targetImage;
    /// <summary>
    /// The last Aliyun-Shanghai url generated by this Applet.
    /// </summary>
    private string imageUrl;

	public AliyunApplet(string key, string secret)
	{
        this.key = key;   // AccessKeyID here
        this.secret = secret;   // AccessKeySecret here
    }

    /// <summary>
    /// Convert a local uri to Aliyun-Shanghai URL,
    /// the standard input format expected by the Aliyun Computer Vision API.
    /// </summary>
    /// <param name="localUri"> The URI to be converted. Can be on the local storage or internet.</param>
    /// <param name="path"> The pointer where the converted path will be recorded.</param>
    /// <returns> The Aliyun-Shanghai URL when returning true, or an error message with false returned if the conversion failed. </returns>
    public bool LocalUriImageToAliyunUrl(string localUri, out string path)
    {
        this.targetImage = localUri;

        try
        {
            FileUtils fileobj = FileUtils.getInstance(key, secret);
            path = fileobj.Upload(localUri);
            this.imageUrl = path;
            return true;
        }
        catch (Exception e)
        {
            path = e.Message;
            return false;
        }
    }

}
